### ISSUE TITLE
Enrollment failed: SDK could not access the user AAD token 

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-ios#193] opened 2021-08-12 14:46 UTC
**Describe the bug:**

Our app use MSAL SDK for authentication and then use `registerAndEnrollAccount` to enroll with Intune. Enrollment is working fine for user with in the same Azure AD. But with user from different AD, enrollment is failing with the below error:

``The operation failed because the SDK could not access the user\'s AAD token.  The application should prompt the user for credentials to refresh the user\'s AAD token.``

**Note:** Azure AD app is enabled with option `Accounts in any organizational directory...`. Azure AD app also has this API  permission `DeviceManagementManagedApps.ReadWrite`

**Device:**
- iOS 14.6

**SDK for iOS:**
 - MSAL (1.1.17)
 - Intune SDK 14.6.0

**Comment by abasore** [comment] 2021-08-16 15:28
@parveen-bhatia Does this error occur after the user from the different AD has entered their credentials? Since the app uses registerAndEnrollAccount and handles the MSAL authentication before enrollment, are you able to confirm if the user from the other AD's MSAL authentication is succeeding and a token is acquired?

**Comment by parveen-bhatia** [comment] 2021-08-16 16:25
Yes, authentication with Azure AD using MSAL works fine and i am able to get the access token by using `applicationContext.acquireToken(with`. After that on call of  `registerAndEnrollAccount`, delegate method `enrollmentRequest(with status: IntuneMAMEnrollmentStatus)` is being called where i am getting that error.

**Comment by Abhinay1997** [comment] 2021-08-18 07:31
I have the same issue. However the `loginAndEnroll` works fine i.e authentication and enrollment both handled by Intune SDK.

**Comment by parveen-bhatia** [comment] 2021-08-20 18:28
Thanks @Abhinay1997, but as per [documentation](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#apps-that-do-not-use-adal-or-msal) we should use `loginAndEnrollAccount` if App doesn't already use ADAL or MSAL. 
But our app use MSAL for authentication first.

Are you also using MSAL for authentication before calling `loginAndEnrollAccount` and does it ask for authentication again ?

**Comment by parveen-bhatia** [comment] 2021-08-24 22:31
I tried this workaround. It fixes the issue for me too and i am not being prompted for authentication again.
Thanks @Abhinay1997

However i hope that SDK will fix this issue with `registerAndEnrollAccount` also.

**Comment by Abhinay1997** [comment] 2021-08-25 02:41
@parveen-bhatia glad to know it worked for your use-case ! 

But you are right, If `registerAndEnrollAccount` is fixed, it will help us out.

**Comment by Abhinay1997** [comment] 2021-08-31 06:06
Hi @abasore, 

I have tried multiple users on the same Azure AD on the same device. The issue persists. And yes, the app configures MSAL to use WKWebView.

**Comment by abasore** [comment] 2021-11-09 14:58
@parveen-bhatia can you confirm if you are still seeing this issue?

**Comment by abasore** [comment] 2021-11-29 16:18
Closing this issue for now. Feel free to create a new issue or reopen if problem persists.

**Closed by abasore** 2021-11-29 16:18 UTC

**Comment by sudeepngeorge** [comment] 2022-08-30 08:37
Hey, I'm still facing the same issue.. Anybody has got a fix for this?

Im getting the below error when calling registerAndEnrollAccount after MSAL acquireTokenWithParameters.
The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token.

**Comment by sudeepngeorge** [comment] 2022-09-01 08:27
> Hey, I'm still facing the same issue.. Anybody has got a fix for this?
> 
> Im getting the below error when calling registerAndEnrollAccount after MSAL acquireTokenWithParameters. "The operation failed because the SDK could not access the user's AAD token. The application should prompt the user for credentials to refresh the user's AAD token."
> 
> Also in IntuneMAMEnrollmentStatus error object it returns below error. Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=No account provided for the silent request. Please call interactive acquireToken request to get an account identifier before calling acquireTokenSilent.}

Anybody who fails to registerAndEnrollAccount after MSAL, try configuring webviewType to MSALWebviewTypeAuthenticationSession like below. It worked for me.
```
    MSALWebviewParameters *webParameters = [[MSALWebviewParameters alloc] initWithAuthPresentationViewController:[self topViewController]];
    webParameters.webviewType = MSALWebviewTypeAuthenticationSession;
```

**Comment by bhargavbajani** [comment] 2023-01-31 21:07
@abasore  yes facing same issue.

**Comment by bhargavbajani** [comment] 2023-01-31 21:08
@parveen-bhatia  can you share some detail on how you managed this issue?
and how you get access token and policy both ?

**Comment by alexeystrakh** [comment] 2023-05-02 21:19
@abasore I have the same issue when calling `registerAndEnrollAccount`:

> The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token.

Based on log from this and other tasks I have checked the following:

- My user is properly authenticated via MSAL prior this call and valid access token is used in the app prior the call
- I'm using MSAL with WKWebView configured, although I tested it when MS authenticator is part of the MSAL auth process
- The issues is reproducible on both a device and a simulator
- Both `com.microsoft.adalcache` and `com.microsoft.intune.mam` are in my entitlements for keychain sharing groups
- If I call `loginAndEnrollAccount` instead of `registerAndEnrollAccount` after being autheticated with MSAL, I'm still asked to enter credentials one more time and unable to complete this flow with error -50000

My environment:
- MSAL: 1.2.9
- Intune:  17.3.2
- iOS: 16.3.1      

Please confirm if there is an issue/bug with `registerAndEnrollAccount` and if there are some workarounds to this issue?

**Comment by rjvishnu87** [comment] 2023-05-03 05:42
I am also facing the same error, after getting auth token successfully.  
**enrollmentRequest failure 203, error = The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token.**

**Comment by leoslima13** [comment] 2023-05-04 18:59
Same here, is there something that we can do for that work?

I can't even use `LoginAndEnrollAcount` because i'm getting this error `The operation couldn't be completed. (MSALErrorDomain error -50000.)`

So I decided to use MSAL to login and then call `RegisterAndEnrollAccount` but this one gives me this error:
**enrollmentRequest failure 203, error = The operation failed because the SDK could not access the user's AAD token. The application should prompt the user for credentials to refresh the user's AAD token.**

Btw I'm using `Xamarin`

**Comment by scopendo** [comment] 2024-11-26 16:26
Why is this issue closed?

**Comment by t-sakhuja** [comment] 2024-12-19 17:09
I'm also having this issue after getting an auth token successfully using MSAL. `enrollmentRequest failure 203, error = The operation failed because the SDK could not access the user's AAD token. The application should prompt the user for credentials to refresh the user's AAD token.`

**Comment by thuongtv-vn** [comment] 2025-02-27 04:38
I also facing the same issue.

**Comment by Quaybe** [comment] 2025-09-29 16:12
Same issue here as well. Can we reopen this issue, @abasore ?

I call AcquireTokenSilentAsync(), which turns to an interactive login if no token is cached, and log in to our Entra environment succeeds. However, when calling IntuneMAMEnrollmentManager.Instance.RegisterAndEnrollAccountId(objectId), I fail with the same error.

Anyone get this figured out?

**Comment by Quaybe** [comment] 2025-09-30 16:22
I want to follow up on my own comment here. For me, my issue was with someone logging in from the same tenant, so maybe not apples-to-apples, here. My issue ended up being plist.info keys. My error was:

Enrollment StatusCode=MAMEnrollmentStatusAuthRequired Identity= Msg='The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token.' NSError=Domain='MSALErrorDomain' Code=-50002 Localized='The operation couldn’t be completed. (MSALErrorDomain error -50002.)' UserInfo={ MSALErrorDescriptionKey=No account provided for the silent request. Please call interactive acquireToken request to get an account identifier before calling acquireTokenSilent. }

This happened even though I was calling AquireTokenInteractive.

For me, the issue was with my info.plist settings:
<key>IntuneMAMSettings</key>
	<dict>	
		<key>MSALAuthority</key>
		<string>xxxxxx</string>
		<key>MSALClientId</key>
		<string>xxxxxx</string>
		<key>MSALRedirectUri</key>
                <string>xxxxxx</string>
		<false/>
        </dict>

These actually needed to be:
   - ADALAuthority
   - ADALClientId
   - ADALRedirectUri

I had switched these back and forth based on the different articles I'd read while troubleshooting. The MSAL keys worked fine in my new Entra dev environment. However, for whatever reason, our production Entra environment needs those to be ADAL.

Hope this helps someone.
