### ISSUE TITLE
IntuneMAMWalledGardenSwift module Issue with module import or Objective-C bridging header

### ISSUE THREAD

**Issue by wvezey** [msintuneappsdk/ms-intune-app-sdk-ios#47] opened 2019-08-30 23:14 UTC
Getting the error in iOS development

   ```Cannot load module 'IntuneMAMWalledGardenSwift' as 'IntuneMAMSwift'```

in two cases:

- When compiling with an Objective-C bridging header with the single import statement ```#import <IntuneMAMSwift/IntuneMAM.h>```

- When using a module import statement in a file: ```import IntuneMAMSwift```

Using:

- Latest version of Intune SDK
- XCode 10.3
- Swift 5

I received this error a few weeks ago, earlier in app development, and it was solved by simply removing the IntuneMAMSwift and IntuneMAMSwiftStub frameworks from the Linked Frameworks and Libraries list, but keeping it in the Embedded Binaries. That's an odd fix, and it not working now. 

I need to read the Intune-assigned Device Id provided in an App Configuration Policy, and suspect I will need the SDK to do so. Any solid guidance here is much appreciated. Thank you.

**Comment by softwarebouwer** [comment] 2019-09-02 06:07
After upgrading from 11.0.13 to 11.1.2 I'm also getting this error, also with a new test project.

**Comment by Kyle-Reis** [comment] 2019-09-03 15:45
Hey folks, I think I've found the root cause of this issue. I think it only applies to Simulator builds. Could you verify that it does not reproduce when building for a physical device?

**Comment by wvezey** [comment] 2019-09-03 19:23
Kyle, allow me to be the first to thank you humbly for your part in bringing Skynet to its knees.

That worked! I was able to build to my iPhone, and to build an archive. The simulator build fails with the same error. I get the same results, whether using an Objective-C bridging header, or an import statement in a file.

Is a fix for simulator builds likely?

**Comment by Kyle-Reis** [comment] 2019-09-03 19:25
@wvezey, yep I already have a fix in review. And you're welcome for the whole saving the human race thing :)

**Comment by softwarebouwer** [comment] 2019-09-04 06:48
Yes, device builds work for me too.

**Comment by wvezey** [comment] 2019-09-05 18:40
@Kyle-Reis do you have a sense when your fix will be merged in? Thanks.

**Comment by gaurav17281** [comment] 2019-09-05 21:53
Same here, I'm also seeing the same issue.

**Comment by Kyle-Reis** [comment] 2019-09-09 20:12
We are working on getting this released within the week.

**Comment by Kyle-Reis** [comment] 2019-09-13 20:56
This issue is fixed in the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases) (11.2.0)

**Closed by Kyle-Reis** 2019-09-13 20:56 UTC
