### ISSUE TITLE
Classes cannot be found when linking Static Library

### ISSUE THREAD

**Issue by StuSharpe** [msintuneappsdk/ms-intune-app-sdk-ios#326] opened 2023-04-05 02:16 UTC
After dragging these libraries into the project, as per instructions for ["Option 2: Static Library" in the setup docs](https://learn.microsoft.com/en-gb/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app):
* `libIntuneMAMSwift.xcframework`
* `IntuneMAMSwiftStub.xcframework`

The expected classes cannot be found (e.g.  'IntuneMAMEnrollmentManager' - see screenshot).

Is there an extra build setting required to make the headers in the static library visible?

This problem doesn't occur if using the regular `InTuneMAMSwift.xcframework` ( "Option 1: Framework" )

- iOS native codebase (Swift/Obj-c)
- Xcode 14.2
- msintuneappsdk/ms-intune-app-sdk-ios 17.3.2

<img width="1123" alt="Screen Shot 2023-04-05 at 1 07 07 PM" src="https://user-images.githubusercontent.com/30331401/229964725-17022f62-2fd2-4db8-a4ef-9ee341bb4bd7.png">

<img width="625" alt="Screen Shot 2023-04-05 at 1 07 31 PM" src="https://user-images.githubusercontent.com/30331401/229964745-8a26dc57-9222-448c-992f-cdb860eff37d.png">

**Comment by abasore** [comment] 2023-04-05 17:25
@StuSharpe have you set the 'Header Search Paths' and 'Library Search Paths' to reference the static lib and headers embedded in the Intune xcframework? Additionally, adding a reference to the headers ('libIntuneMAMSwift.xcframework/ios-arm64/Headers') to the 'Headers' step under 'Build Phrase' will include the headers as build dependencies in the project.

**Comment by StuSharpe** [comment] 2023-04-05 22:11
Hi @abasore, thanks for getting back to us.

I've tried a lot of options regards header search paths.  Including both the 'Header Search Paths' and 'Library Search Paths'  (and any other header search path i can find).  Have also tried adding the headers path (and framework) to the 'Headers' section in the 'Build Phases'.  None of these worked.  (See attached screenshots. )

However, I finally managed to get it to work by creating a bridging header that refs the root header file:
```
#import "libIntuneMAMSwift.xcframework/ios-arm64/Headers/IntuneMAM.h"
```

Although this seems to solve the issue in the meantime, it seems a bit hacky:
 - Should the bridging header be necessary in this case?  
 - If so, hard-coding the entire lib header path seems a bit ugly, is there a better recommended way to do this?

<img width="921" alt="Screen Shot 2023-04-06 at 9 26 47 AM" src="https://user-images.githubusercontent.com/30331401/230222745-75c7d2ea-d855-4cb4-83c1-2e8777fce576.png">

<img width="894" alt="Screen Shot 2023-04-06 at 10 07 56 AM" src="https://user-images.githubusercontent.com/30331401/230222859-60ef6264-3907-4658-bcc3-279e89ea2f52.png">

**Comment by abasore** [comment] 2023-04-07 21:06
@StuSharpe Yes, since the IntuneMAMSDK is in Objective C, the the bridge header would import the library headers into be callable from swift. As for the header paths, one option would be to create a custom build variable that you could use to shorten all the paths. For example: 
<img width="828" alt="Screenshot 2023-04-06 at 11 38 41 AM" src="https://user-images.githubusercontent.com/73957018/230678924-70676062-cd1d-42ac-9f88-dd9356b874cb.png">

**Comment by abasore** [comment] 2023-04-10 17:05
Ill go ahead and close this since the bridge header worked for you @StuSharpe.

**Closed by abasore** 2023-04-10 17:05 UTC

**Comment by arnauZurich** [comment] 2024-03-07 17:37
Hi,

I'm facing the same issue in the Intune example app (Chatr). I have tried all the workarounds exposed here, but none of them have worked for me. Could you help me?

xcode version: 15
Intune version: 19.0.0

How to reproduce:
1. Download the intune example app: [Chatr app](https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App)
2. Try to use static library instead dynamic: [Option 2 - Static Library](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#build-the-sdk-into-your-mobile-app)

**Comment by alloza95** [comment] 2024-03-08 12:47
Same issue here! Should this issue be reopened?

**Comment by juansoilan** [comment] 2024-03-11 15:31
With xCode 15.3 I have the same problem, using the dynamic libraries it works correctly but with the static module it is not working. I have tried @StuSharpe workaround and also referencing the headers in build settings without success.

**Comment by wangxiaoms** [comment] 2024-04-13 00:21
Please refer to #416 for more information and procedure.
