### ISSUE TITLE
User encounters interaction required MSAL error during token attempt

### ISSUE THREAD

**Issue by viwod** [msintuneappsdk/ms-intune-app-sdk-ios#407] opened 2024-03-06 18:59 UTC
**Describe the bug:**
We have a flow that involves acquiring a token post enrollment. We register for the enrollmentRequest callback via an IntuneMAMEnrollmentDelegate. Once we get a callback with a status code indicating the user has successfully enrolled with our app, we begin the token acquisition process. We are able to properly configure an MSALPublicClientApplication and use it to acquire a token (via acquireTokenSilent). However, we receive an interactionRequired MSALError during this step. We do not have two factor authentication enforced for the user. How can we get past this error and proceed?

**To Reproduce**
1. Enroll Intune account with app
2. Configure MSALPublicClientApplication
3. Attempt to acquire token via acquireTokenSilent
4. See interactionRequired MSALError

**Expected behavior:**
Proceed with token acquisition without error

**Smartphone (please complete the following information):**
 - Device: [iPhone 15]
 - OS: [iOS 17]

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes (19.1.0)
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Native
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by wangxiaoms** [comment] 2024-03-11 03:30
Besides two factor authentication there are other reasons for the interactionRequired MSALError, e.g. Content Required. Normally after receiving that error user needs to acquire token interactively. If there is any issue with the flow please share more details.

**Comment by viwod** [comment] 2024-03-11 17:59
Currently, we have a user that is targeted by an app protection policy and has a conditional access policy granted. This policy also has our app whitelisted already. As mentioned above, we are able to successfully generate a MSALPublicClientApplication and use it to acquire a token via acquireTokenSilent. It's at this step that we encounter the InteractionRequired error.

And sure, what additional information do you need? And is there some other object I should be querying to get more details on this error outside of the error object we're seeing?

**Comment by wangxiaoms** [comment] 2024-03-12 00:14
interactionRequired can be caused by reasons like Consent Required, after receiving that error acquireToken with interactive flow should be used. Could you clarify why this is an issue?

**Comment by viwod** [comment] 2024-03-12 04:02
At this point in the flow we're stopping when receiving this because we're expecting an access token for the expected account identifier. Would you mind referencing the documentation for this specific interactive flow you're referring to?

**Comment by wangxiaoms** [comment] 2024-03-12 04:17
You can refer to below documents: 
https://github.com/AzureAD/microsoft-authentication-library-for-objc?tab=readme-ov-file#responding-to-an-interaction-required-error
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-ios#get-a-token-silently

**Comment by viwod** [comment] 2024-03-12 04:40
Thanks for your response, with our silent token acquisition we are attempting to reduce the auth steps/the amount of steps the user needs to take before acquiring this auth token. We'd like to avoid this additional step as much as possible. We've noticed that for some users we are able to acquire this token silently, and for other users we see this interaction required error. 

What is the exact cause of this error? Is this because the user has some setting in their tenant/conditional access policy etc. that prevents them from acquiring a token via this silent token acquisition function?

**Comment by wangxiaoms** [comment] 2024-03-12 23:44
You can get more information from the error object, e.g. the subError - error.userInfo[MSALOAuthSubErrorKey]
https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/MSALError.h
As an example consent_required, once user grants the permission, next time silent token acquisition will be successful.

**Comment by viwod** [comment] 2024-03-14 07:36
Thanks @wangxiaoms. We'll repro the error and fetch that to see what the exact cause of the interaction requirement is

**Comment by viwod** [comment] 2024-03-14 08:09
Outside of multi factor authentication and consent required (the user seeing this error does not have MFA enforced and we also have granted consent), what are other possible causes for this interaction required error to appear? Is there documentation somewhere with all potential scenarios that could result in this interaction required error?

**Comment by wangxiaoms** [comment] 2024-03-14 09:08
There is a doc (.NET) for reference:
https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/exceptions/msal-error-handling#msaluirequiredexception-classification-enumeration

**Comment by wangxiaoms** [comment] 2024-03-25 05:04
As the questions are answered I will close the issue.

**Closed by wangxiaoms** 2024-03-25 05:04 UTC
