### ISSUE TITLE
Cannot find IntuneMAM.framework

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#145] opened 2021-02-22 15:02 UTC
**Describe the bug:**
Cannot find the latest IntuneMAM.framework in the folder or from https://github.com/msintuneappsdk/ms-intune-app-sdk-ios.git

**Comment by Nookaraju** [comment] 2021-02-22 15:04
@Kyle-Reis can you please check this? I'm trying to replace the old IntuneMAM.framework with a new one and I cannot find it.


Btw, old SDK(v 12.8.0) gives below error:

The Intune MAM SDK failed to connect to the location service to determine the user's endpoint, see error object for details

**Comment by Kyle-Reis** [comment] 2021-02-22 15:16
Hi @Nookaraju, with the [current release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the Intune SDK, all apps (both Objective-C and Swift) can now link to IntuneMAMSwift.xcframework and IntuneMAMSwiftStub.xcframework. Please refer to our [updated integration instructions](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app). Note: Minimum supported iOS version for Intune is now iOS 12.2, so the app's target OS should be updated accordingly.

xcframeworks have several benefits compared to old FAT binaries:
- Support for building with latest versions of Xcode (see issue #130)
- Support for simulator on new Apple Silicon Macs
- Developers no longer need to strip out simulator architectures from the Intune framework when submitting to the app store or pushing to production. Xcode handles this automatically. 
- No need to set up header search paths for the static library version of the SDK (libIntuneMAMSwift.xcframework). Xcode handles this automatically.

**Comment by Nookaraju** [comment] 2021-02-22 15:25
@Kyle-Reis I used them and updated min. target to 12.2.

Now it gets crashed on IntuneMAMEnrollmentManager.instance().enrolledAccount() BAD accesss.

**Comment by Kyle-Reis** [comment] 2021-02-22 22:05
Hi @Nookaraju, are you able to reproduce the crash consistently? If so could you open a service request by going to "Troubleshooting + support" -> "Help and support" -> "Intune" in Endpoint Manager? We'll likely need to take a look at Intune logs for your app to figure out what's going on. If you could collect them by calling the API mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app) and provide them to our support team that will be really helpful. A crash log will also help with the investigation if you can provide it.

**Comment by Nookaraju** [comment] 2021-02-23 10:23
'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/Library/Developer/CoreSimulator/Devices/D907FB85-B968-48AC-85DB-A9B5D4E9A46F/data/Containers/Bundle/Application/164D6CFF-1A1E-4E80-93C3-C3C8950A9775/app.app> (loaded)' with name 'PolicyViewController_iPhone''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2041daf2 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2041d9d0 -[NSException initWithCoder:] + 0
	3   UIKitCore                           0x00007fff24275a9f -[UINib instantiateWithOwner:options:] + 495
	4   UIKitCore                           0x00007fff23f40b48 -[UIViewController loadView] + 668
	5   UIKitCore                           0x00007fff23f40ee3 -[UIViewController loadViewIfRequired] + 172
	6   UIKitCore                           0x00007fff23f4165d -[UIViewController view] + 27
	7   UIKitCore                           0x00007fff246b3d0f -[UIWindow addRootViewControllerViewIfPossible] + 313
	8   UIKitCore                           0x00007fff246b33fd -[UIWindow _updateLayerOrderingAndSetLayerHidden:actionBlock:] + 219
	9   UIKitCore                           0x00007fff246b43c1 -[UIWindow _setHidden:forced:] + 362
	10  UIKitCore                           0x00007fff246c73d4 -[UIWindow _mainQueue_makeKeyAndVisible] + 42
	11  IntuneMAMSwift                      0x0000000106499408 initializeShareExtensionHooks + 5489
	12  IntuneMAMSwift                      0x00000001064b63b7 initializeUIGraphicsHooks + 10691
	13  IntuneMAMSwift                      0x000000010638e80e initializeScreenshotServiceHooks + 37906
	14  IntuneMAMSwift                      0x000000010638e8c5 initializeScreenshotServiceHooks + 38089
	15  IntuneMAMSwift                      0x00000001064f0a50 initializeSceneConnectionOptionHooks + 10960
	16  IntuneMAMSwift                      0x00000001064ef5b9 initializeSceneConnectionOptionHooks + 5689
	17  IntuneMAMSwift                      0x000000010638e56d initializeScreenshotServiceHooks + 37233
	18  libdispatch.dylib                   0x00000001067cd7ec _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x00000001067ce9c8 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x00000001067dce75 _dispatch_main_queue_callback_4CF + 1152
	21  CoreFoundation                      0x00007fff2038bdab __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff2038662e __CFRunLoopRun + 2685
	23  CoreFoundation                      0x00007fff203856c6 CFRunLoopRunSpecific + 567
	24  GraphicsServices                    0x00007fff2b76adb3 GSEventRunModal + 139
	25  UIKitCore                           0x00007fff24675187 -[UIApplication _run] + 912
	26  UIKitCore                           0x00007fff2467a038 UIApplicationMain + 101
	27  IntuneMAMSwift                      0x00000001064fb903 Intune_UIApplicationMain + 210
	28  Infor Go                            0x000000010458e1b5 $s8Infor_GoySpySpys4Int8VGGXEfU_ + 245
	29  Infor Go                            0x000000010458e1ef $sSpySpys4Int8VGGs5Error_pIgyzo_ADytsAE_pIegyrzo_TR + 15
	30  Infor Go                            0x000000010458e244 $sSpySpys4Int8VGGs5Error_pIgyzo_ADytsAE_pIegyrzo_TRTA + 20
	31  libswiftCore.dylib                  0x00007fff2f23117f $sSP17withMemoryRebound2to8capacity_qd_0_qd__m_Siqd_0_SPyqd__GKXEtKr0_lF + 15
	32  libswiftCore.dylib                  0x00007fff2f40988f $sSp17withMemoryRebound2to8capacity_qd_0_qd__m_Siqd_0_Spyqd__GKXEtKr0_lF + 15
	33  Infor Go                            0x000000010458e063 main + 291
	34  libdyld.dylib                       0x00007fff20256409 start + 1
	35  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/nmaddila/Library/Developer/CoreSimulator/Devices/D907FB85-B968-48AC-85DB-A9B5D4E9A46F/data/Containers/Bundle/Application/164D6CFF-1A1E-4E80-93C3-C3C8950A9775/App.app> (loaded)' with name 'PolicyViewController_iPhone''
terminating with uncaught exception of type NSException
CoreSimulator 732.18.0.2 - Device: iPhone 12 (D907FB85-B968-48AC-85DB-A9B5D4E9A46F) - Runtime: iOS 14.2 (18B79) - DeviceType: iPhone 12

**Comment by Nookaraju** [comment] 2021-02-23 10:35
It's still referencing to old SDK. Deleted OLD SDK and used the xcframeworks. 

But now, It gives me some error like the below:
![Intune Error](https://user-images.githubusercontent.com/2161122/108831984-e769bf00-75f0-11eb-985c-ab18f3929d37.png)

**Comment by Kyle-Reis** [comment] 2021-02-23 15:47
Hi @Nookaraju, did you also update the version of ADAL linked by the app?

**Comment by Kyle-Reis** [comment] 2021-02-23 16:04
@Nookaraju, this issue can be addressed by adding a redirect URI to the app registration in AAD which matches the above format:

1.) Go to portal.azure.com and sign in with an admin account for the tenant where your app's client ID is registered.
2.) Select "Azure Active Directory"
3.) Select "App registrations"
4.) Find the app registration for your app.
5.) Select the link next to "Redirect Uris"
6.) Under "Mobile and desktop applications", add a redirect URI which is in the format specified above.
Note: Don't use the iOS/macOS section to generate the redirect URI, as it will create a redirect URI for use with MSAL (unless you want to move over to MSAL now).

In your app:
1.) Update the redirect URI used by the app and for Intune enrollment to the newly created one which is in the format [custom scheme]://[bundle ID]
2.) Add the scheme of the new redirect URI to CFBundleURLSchemes in the app's Info.plist

**Comment by Nookaraju** [comment] 2021-02-23 18:42
@Kyle-Reis I did this and it worked but I am wondering why the redirect URI should be [custom scheme]://[bundle ID]??

It used to work earlier with [custom scheme]://[anything here].

**Comment by Kyle-Reis** [comment] 2021-02-23 19:13
Was the version of ADAL changed recently?

**Comment by Nookaraju** [comment] 2021-02-24 05:54
No

**Closed** 2021-02-24 12:16 UTC

**Comment by dil-asagar** [comment] 2022-03-24 16:55
> Hi @Nookaraju, with the [current release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the Intune SDK, all apps (both Objective-C and Swift) can now link to IntuneMAMSwift.xcframework and IntuneMAMSwiftStub.xcframework. Please refer to our [updated integration instructions](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app). Note: Minimum supported iOS version for Intune is now iOS 12.2, so the app's target OS should be updated accordingly.
> 
> xcframeworks have several benefits compared to old FAT binaries:
> 
>     * Support for building with latest versions of Xcode (see issue [Dynamic Library Support Xcode 12.3 #130](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/130))
> 
>     * Support for simulator on new Apple Silicon Macs
> 
>     * Developers no longer need to strip out simulator architectures from the Intune framework when submitting to the app store or pushing to production. Xcode handles this automatically.
> 
>     * No need to set up header search paths for the static library version of the SDK (libIntuneMAMSwift.xcframework). Xcode handles this automatically.



> 

we are getting an error on app submission `ERROR ITMS-90085: "No architectures in the binary. Lipo failed to detect any architectures in the bundle executable`

Its looks like on Version 15.4.0 >> Its not doing the "strip out simulator architectures " correctly. Anyone knows a solution?
