### ISSUE TITLE
App Crashing on launch

### ISSUE THREAD

**Issue by ashishhasija** [msintuneappsdk/ms-intune-app-sdk-ios#164] opened 2021-05-07 09:26 UTC
Description:
I have integrated Intune SDK to my app. It was working fine till last week. The App is showing an error message on launch and gets blocked on the screen(refer screenshot2). Note that the Live version of the app is working fine. The crash is reproducing on the POC version. Live and POC version of the apps are registered as separate entities on Azure Portal.

1. Launch application
4. See error on screenshot2

**Expected behavior:**
App should launch as expected. 

**Screenshots and logs:**
![screenshot2](https://user-images.githubusercontent.com/14230886/117429186-a426a900-aedb-11eb-913c-ebdae671fdd9.jpg)

**Comment by Kyle-Reis** [comment] 2021-05-07 17:23
Hi @ashishhasija, is the user prompted for credentials after they select "OK" in the screenshot above? Which version of the Intune SDK is the POC using?

**Comment by patlewis-MSFT** [comment] 2021-05-07 19:18
@ashishhasija you mentioned the two apps are registered differently. Are you sideloading the non working one? If so have you also uploaded the app with the Intune (MEM) portal and applied an app protection policy if applicable and assigned to the user?

**Comment by ashishhasija** [comment] 2021-05-10 02:19
> Hi @ashishhasija, is the user prompted for credentials after they select "OK" in the screenshot above? Which version of the Intune SDK is the POC using?

The user is supposed to see the login screen (to enter credentials on). But the app crashes instead. We are using Intune SDK version 14.1.3.

**Comment by ashishhasija** [comment] 2021-05-10 02:22
> @ashishhasija you mentioned the two apps are registered differently. Are you sideloading the non working one? If so have you also uploaded the app with the Intune (MEM) portal and applied an app protection policy if applicable and assigned to the user?

We have registered the POC and Live app as 2 different entities on Azure portal having their separate client IDs. I've tried pushing the POC app through Intune MEM and installing it through AppCenter portal directly. I still face the crash in either case.

**Comment by ashishhasija** [comment] 2021-05-10 12:56
UPDATE: I was able to fix the crash by removing "com.microsoft.intune.mam" from the keychain sharing. But my app seems to be not managed anymore. 

Could you tell me whats the reason for the crash. 
Also, help me with a real solution so that my app stays managed?

**Comment by Kyle-Reis** [comment] 2021-05-10 13:55
@ashishhasija - The "com.microsoft.intune.mam" keychain access group is required for the Intune SDK to function properly. Could you check if the issue reproduces with the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of Intune (version 14.3.5)? If the issue persists, could you also share the version of ADAL or MSAL that the app is linking to?

**Comment by VaibhavMisraEZ** [comment] 2021-05-11 14:09
@Kyle-Reis - I work @ashishhasija on the same team. We tried integrating Intune 14.3.5 today, yet the issue persists. We have integrated with ADAL v2.7.17. The home screen has a login button, tapping which we initiate login through ADAL. However, even the home screen is not shown and we are directly shown the error screen. The app crashes afterwards.

Following is the console output:

> 2021-05-11 10:37:08.040804+0530 SampleApp[360:9996] Unbalanced calls to begin/end appearance transitions for <CMARPolicyViewController: 0x1068b3800>.
2021-05-11 10:37:09.332231+0530 SampleApp[360:10234] writeDBwithCachedResponse - Invalid protocol-property list - CFURLRequestRef. protoProps={
    context = "<ADWebAuthRequest: 0x282004b40>";
}
2021-05-11 10:37:09.334564+0530 SampleApp[360:9996] -[WKWebView setDelegate:]: unrecognized selector sent to instance 0x107096a00
2021-05-11 10:37:09.334981+0530 SampleApp[360:9996] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebView setDelegate:]: unrecognized selector sent to instance 0x107096a00'
*** First throw call stack:
(0x1b05fb9d8 0x1c497eb54 0x1b050bbbc 0x1b2e9ad30 0x1b05fe01c 0x1b05fff8c 0x105850380 0x10586d708 0x10586dc8c 0x106333ce4 0x106335528 0x106343994 0x1b057b5e0 0x1b0575a88 0x1b0574ba0 0x1c72da598 0x1b2e662f4 0x1b2e6b874 0x10605683c 0x1016c913c 0x1b0253568)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebView setDelegate:]: unrecognized selector sent to instance 0x107096a00'
terminating with uncaught exception of type NSException

Please let us know if you need more information.

**Comment by Kyle-Reis** [comment] 2021-05-11 14:31
@VaibhavMisraEZ - It looks like the application is attempting to call setDelegate on a WKWebView, and since WKWebView has not such property, this causes a crash. I'm guessing the app is inadvertently obtaining a reference to the WKWebView from the ADAL auth prompt that Intune is displaying on launch to refresh the MAM access token, and it expects to be referencing a different class. Could you check to see if something like this is happening in the app's code in willFinishLaunching? If so, is it possible for the logic to be moved out to didFinishLaunching?

**Comment by VaibhavMisraEZ** [comment] 2021-05-13 11:33
@Kyle-Reis - Thank you for your quick replies. Few observations below:

1. We do not have any code in 'willFinishLaunching'
2. We do not use Intune for login. Instead we handle login ourseleves using ADAL. On successful login, we use IntuneMAMEnrollmentManager's registerAndEnrollAccount method.
3. On login screen (landing screen), there's just a login button. We don't setup either ADAL or Intune SDK beforehand. We only initiale ADAL when user taps the login button. We then setup Intune registration after successful login. Hence, the screenshot attached shouldn't ideally have come before these steps.
4. I retried the app with Intune SDK v14.3.5. Interestingly, it showed similar screen, however, this time the alert was different. I forgot to take a screenshot, but it said something like this: "Do you allow your organization to manage this app's data..". The alert had 2 buttons, namely, 'Cancel' and 'Manage'. I tapped on 'Manage' button, the app crashed again. However, since then the app is working fine. Even if I delete the app and install previous version of the app with Intune SDK v14.1.3, it works fine. I am no longer getting the above screenshot.

I will try to recreate this on other devices and update you if anything changes. However, it makes me think, there is some unhandled scenario on v14.1.3 which doesn't let the app proceed. It's partially fixed in v14.3.5, by showing that new alert. However, the crash there after makes me think the fix is not complete. The scenario could have happened due to changes in settings from Intune Portal or incorrect integration of the SDK. I am not yet sure of it. This is all my hypothesis and I could be totally wrong. :)

**Comment by VictorKimbi** [comment] 2023-03-01 07:48
@Kyle-Reis  - I am experiencing similar issue, the app goes to background not crashing necessarily we using IntuneSDK 17.3.1 now. The application is is hosted in Intune Company portal and in Testflight as well.

**Comment by ShruthiAchutha** [comment] 2024-02-23 17:00
Closing stale issues. Please reopen if you still need help with this.

**Closed by ShruthiAchutha** 2024-02-23 17:00 UTC
