### ISSUE TITLE
Behaviour after Intune MAM SDK implementation

### ISSUE THREAD

**Issue by gambarle** [msintuneappsdk/ms-intune-app-sdk-ios#152] opened 2021-03-05 15:25 UTC
Hi

I'm running an Ionic 3 Angular app.

I have incorporated the ms-intune-app-sdk-ios-14.1.3, using the `IntuneMAMSwift.xcframework` library, in XCode 12.

I have also build a plugin for the app in order to use Objective C, to call the `[[IntuneMAMEnrollmentManager instance] registerAndEnrollAccount:@"user@foo.com"];` method, in the SDK.

I have also set up a protection policy for a custom app, according to the instructions here[here](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies#:~:text=In%20the%20App%20protection%20policies%20pane%2C%20select%20the,apply%20this%20policy%20to%20apps%20on%20different%20devices.)

However, when I acces the method call in my app, to login and enroll the user account, I only get a splash screen for a split second (see attached img), saying "Checking your organization's data access requirements for this app". But nothing else happens.

What behaviour should I expect at this point in the app?
Is there anything more I need to set up in the MS Endpoint admin center?

Best regards
![Image from iOS](https://user-images.githubusercontent.com/1540031/110135969-6cae5a00-7dcf-11eb-81f4-97022f2d0cf7.png)

**Comment by neiljac1** [comment] 2021-03-05 15:57
Hi @gambarle. Are you calling loginAndEnrollAccount or registerAndEnrollAccount? The registerAndEnrollAccount API silently tries to enroll the account you pass in. It requires the application to log the user in before calling it. The loginAndEnrollAccount API will display the UI in the screenshot, try to silently enroll the application, and if this fails displays a login page for the user to authenticate. Both APIs require either MSAL or ADAL to be linked into your application. If the UI above flashes briefly, it could be that the SDK contacted the service and found there were no policies targeted to the user+application, or it could mean that MSAL/ADAL was not linked into the application and authentication failed.

If ADAL/MSAL was not properly linked into your application, you should see the following line in the Intune logs: 
"Failed to create an AD Authentication Context instance". 

If the SDK was able to contact the service and there were no policies assigned to the user+application, then you'd see this in the log:     
Commands =     (
                {
            Name = NoPolicy;
            Value = "";
        }
  );

To access the Intune logs, call [IntuneMAMDiagnosticConsole displayDiagnosticConsole]. This will display a screen which will allow you to share the Intune logs via iOS's standard share sheet.

**Comment by gambarle** [comment] 2021-03-09 11:21
Hi @neiljac1.
Thank's for your response.
I am using "loginAndEnrollAccount", since our app is not using ADAL or MSAL, for authentication users.
I was under the impression, that using "loginAndEnrollAccount" is sufficient in this situation, from the MAM iOS [documentation](https://docs.microsoft.com/da-dk/mem/intune/developer/app-sdk-ios#status-result-and-debug-notifications), where it states: 

> "Apps that do not sign in the user using ADAL or MSAL can still receive app protection policy from the Intune MAM service by calling the API to have the SDK handle that authentication."

Previously, I did create a protection policy, for our app bundle ID, and added a user group, that my user is a member of, and when I look at myaccount.microsoft.com, under devices, I can see my current iPhone listed as managed by Intune.

I have now gotten the Intune logs from my iOS device, and neither, 
"Failed to create an AD Authentication Context instance", or 
"Commands = ({Name = NoPolicy;Value = "";});"
Is found in them, however there are indications that something is not right.
I will attach them, in case they show any clarifying information.

At this point, I'm not sure wether the obstacle is caused by the device not being properly authenticated (MSAL/ADAL), or it is to do with my MS/Intune account, but any insights are much appreciated.

Best regards
[IntuneMAMDiagnosticFiles 2.pdf](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/6108072/IntuneMAMDiagnosticFiles.2.pdf)

**Comment by gambarle** [comment] 2021-03-09 20:01
Thanks again @neiljac1,
That makes sense, but how do I then link the app against MSAL/ADAL?
Is that to do with the protection policy, or is it my user?

Best regards

**Comment by gambarle** [comment] 2021-03-10 07:49
Thx @neiljac1 
Ok, understanding the linking now, and I'm sorry to be such a drag, but how do I build MSAL/ADAL?

Best regards

**Comment by neiljac1** [comment] 2021-03-10 15:29
The MSAL source code can be found here: https://github.com/AzureAD/microsoft-authentication-library-for-objc

**Comment by gambarle** [comment] 2021-03-10 15:59
Thx @neiljac1 

Ok, so I have gone back to the documentation (Intune app SDK for iOS), and I have registered our app in the azure portal, with a redirect URI, in the format `msauth.[BUNDLE_ID]://auth`
The AzureAD MSAL readme also states, that I can install it manually, by checking out the latest release, but I cannot locate the MSAL.framework. Do I need to build MSAL, as you say above, and how?
If I open `MSAL.xcworkspace` or `MSAL.xcodeproj` in XCode I get errors when I try to build it.

Best regards

**Comment by Kyle-Reis** [comment] 2021-03-10 16:04
Hi @gambarle, it's actually best to link to the MSAL xcframework. The MSAL team actually makes a pre-built xcframework available under MSAL.zip in their [latest release](https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/latest).

**Comment by neiljac1** [comment] 2021-03-10 16:05
Hi @gambarle. Try this link: https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/download/1.1.15/microsoft-authentication-library-for-objc-1.1.15.zip  and build the 'MSAL (iOS Framework)' target.
Thanks, Neil

**Comment by gambarle** [comment] 2021-03-11 14:19
Thx so much @neiljac1 @Kyle-Reis 

I have now linked MSAL to my application(using the MSAL.zip), and set up the redirect URI and permissions for the app. 

The redirect URI in the ADAL app registration is in the format `msauth.[BUNDLE_ID]://auth` which is set automatically when I enter the bundle ID.

If I set the `Printix App-info.plist`->`IntuneMAMSettings`->`ADALRedirectUri` to `msauth.net.printix.printixapp://auth`, I get `Failed to create an AD Authentication Context instance` in the Intune Logs, when running the app.

However, setting `Printix App-info.plist`->`IntuneMAMSettings`->`ADALRedirectScheme` to `https://printixapp`, I get the application logon, for Intune, and can go through adding credentials, but after signing in, I get the error, that the reply URL is not matching the URLs for the application (see screen shot).

The `https://printixapp` redirectUri, is also set as a redirect UrlScheme in the app's config.xml file, for our existing OAuth login procedure. (also set it in ADAL app registration as a redirect scheme under mobile and desktop applications)

I have tried, to add the msauth.[BUNDLE_ID]://auth, format to my config.xml file, but to no avail.

Any thoughts

Best regards
 
![IMG_3910](https://user-images.githubusercontent.com/1540031/110801100-2b112980-827d-11eb-872c-d8d16eb70b5d.PNG)

**Comment by Kyle-Reis** [comment] 2021-03-11 14:51
@gambarle - MSAL requires the msauth.[BUNDLE_ID]://auth format for redirect URI on iOS. Have you followed all of the [configuration instructions for MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal)? It sounds like this could be caused by missing CFBundleURLSchemes or LSApplicationQueriesSchemes entries in the Info.plist.

**Comment by gambarle** [comment] 2021-03-11 19:59
@Kyle-Reis 
Eureka! 
I had totally overlooked the CFBundleURLSchemes and LSApplicationQueriesSchemes, in the documentation, and now it is working.

Thank you so much for all the help, also @neiljac1,  I hope this thread can be of assistance for others, in the same situation.

Best regards

**Comment by Kyle-Reis** [comment] 2021-03-12 19:52
Glad to hear it's been sorted out :) Please reach out if you have any other issues.

**Closed by Kyle-Reis** 2021-03-12 19:52 UTC
