### ISSUE TITLE
Maui App with Intune SDK 19.0.1 iOS does NOT build when build target is a real device

### ISSUE THREAD

**Issue by tomzeni** [msintuneappsdk/ms-intune-app-sdk-ios#399] opened 2024-01-25 12:11 UTC
Maui iOS App with Intune SDK 19.0.1 does NOT build when build target is a real device

## Summary
Currently it is NOT possible to build an MAUI iOS App in VS2022 for "a real iOS Device" when using the Intune SDK iOS 19.0.1
As soon as you add the Intune SDK iOS 19.0.1 NuGet to a Maui.iOS App project, then any following builds will fail with this error message:

MSB3073 The command "./IntuneMAMConfigurator -i obj/Debug/net8.0-ios/ios-arm64/AppManifest.plist -e Entitlements.plist" exited with code 134
./IntuneMAMConfigurator -i obj/Debug/net7.0-ios/ios-arm64/AppManifest.plist -e Entitlements.plist
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'plist parameter is nil'

It looks like the AppManifest.plist is never generated before the IntuneMAMConfigurator is called with the AppManifest.plist in question as a parameter when the build target is a real device.

**To be clear: App will build for any iOS simulator device, but will always fail if you select a real device (e.g. iPhone) as build target (!)**

**Steps to reproduce the behavior:**
Variant a)
1.	Open VS2022 and create a new net Maui App using .net 7 or .net 8
2.	Add “Microsoft.Intune.Maui.Essentials.iOS v19.0.1” via NuGetPackageManager
3.	Select a real iOS device (e.g. iPhone) as build target connected to your mac
4.	Try to build it… it will fail building with the error message metioned above

Variant b)
1.	Just download the sample-intune-maui-ios from your own repo : https://github.com/msintuneappsdk/sample-intune-maui-ios
2.	Select a real iOS device (e.g. iPhone) as build target connected to your mac
3.	Try to build it… it will fail building with the error message metioned above

**Expected behavior:**
Die App should build without Error when the build target is a real iOS device.

**Intune App SDK for iOS (please complete the following information):**

- For errors during build, does the app build without Intune SDK integration?
YES, the app does build without Intune SDK integration

- For errors post build, does the app launch without being Intune SDK integrated?
YES, the app does launch without being Intune SDK integrated

- Who is the customer?
We have a popular app build with Xamarin that some enterprise customers and many medium-sized customers currently use. We urgently need to migrate this App to MAUI, therefor Intune App SDK for MAUI.iOS has to function properly, because our App relies on Conditional  Access -> require App Protection Policy.

- Do you see a trend with it only being reproduced on a specific device?
YES, it can be reproduced on REAL iOS Devices only. 
It cannot be reproduced on iOS simulators

## Details

- Test Devices: iPhone 13 @ iOS17.2.1 / iPhone 13 @iOS17.3 / iPhone XR @iOS17.1.1
- Microsoft.Intune.Maui.Essentials.iOS Version: 19.0.1
- Build Operating System (Mac, Windows) and Version: macOS Sonoma 14.2.1 and XCode 15.1 / Win 11 Enterprise 21H2
- Visual Studio Version: VS 2022 LTSC 17.8  for Windows / VS 2022 17.9.0 Preview 4.0

## Screenshots and logs

- If your app is experiencing an issue during build, do you have app logs for the crash itself?  
MSB3073 The command "./IntuneMAMConfigurator -i obj/Debug/net8.0-ios/ios-arm64/AppManifest.plist -e Entitlements.plist" exited with code 134
1>./IntuneMAMConfigurator -i obj/Debug/net8.0-ios/ios-arm64/AppManifest.plist -e Entitlements.plist 1>*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'plist parameter is nil' 1>*** First throw call stack: 1>( 1>	0 CoreFoundation 0x00007ff80894d89e __exceptionPreprocess + 242 1> 1 libobjc.A.dylib 0x00007ff80844067f objc_exception_throw + 48 1> 2 Foundation 0x00007ff809f2a664 +[NSPropertyListSerialization writePropertyList:toStream:format:options:error:] + 204 1>	3 IntuneMAMConfigurator 0x00000001026557be writePropertyList + 161 1>	4   IntuneMAMConfigurator               0x000000010265084e configureInfoPlist + 862 1> 5 IntuneMAMConfigurator 0x0000000102650cf9 main + 393 1> 6 dyld 0x0000000202685386 start + 1942 1>) 1>libc++abi: terminating due to uncaught exception of type NSException

- If your app is experiencing an issue post build, do you have app logs for the crash itself?
NO, as the app does not build at all

We are grateful for any suggestions or help

Thanks a lot!

**Comment by Kyle-Reis** [comment] 2024-02-01 17:11
Closing this issue out as it is a duplicate of #395. Will track this there.

**Closed by Kyle-Reis** 2024-02-01 17:11 UTC
