### ISSUE TITLE
Text message not appear with passed text 

### ISSUE THREAD

**Issue by rooneytx** [msintuneappsdk/ms-intune-app-sdk-ios#127] opened 2020-12-07 21:47 UTC
We have an iOS MAM wrapped application in which trigger an action and expect the iOS native text composer to appear with the pre-populated message. This works when the app is deployed via MDM. But does not work when deployed for MAM.

MAM policy:
Send org data to other apps -> Policy managed apps
Select apps to exempt -> SMS: sms;

MDM Policy:
Send org data to other apps -> All apps

Also what is strange, when we deploy via MAM and don't have the exemption in place the text composer still appears with no text. We would have expect to see the alert " Your organization only allows you to transfer its data to other managed apps." - Why didn't we see this alert consider we are trying to send from an managed app to a non-managed app.

Why when the exempt URL schema is set we are still not seeing the text composer pre-populated. 

SDK version: 12.0.12

using the cordova-sms-plugin

**Comment by Kyle-Reis** [comment] 2021-04-05 22:11
Closing out this issue and using #126 to track it since at the core, they are the same (in this case MFMessageViewController is what the app is attempting to use). At it's core, the problem is that the apps are attempting to use built-in view controllers (in this case MFMessageViewController is what the app is attempting to use) to share data to the native Messages and Mail app when outgoing share policy is restricted to policy-managed apps with exemptions specified for "mailto" and "sms" URL schemes. Although the actual cross-platform code written is attempting to open URLs with those schemes, these calls appear to be getting translated into in-app view controller presentations at the native layer, and since the scheme exemption list currently applies only to URLs, these view controllers are blocked from being presented or data is blocked from being transferred to them. We are considering making a change to allow these VCs to be used when "mailto" or "sms" have been added to the URL scheme exemption list, but there are some concerns about potential inconsistencies this may introduce with regard to file attachments. I will post an update to issue #126 once the team has reached a decision. In the meantime, I would investigate if there's any way to work around or disable the apparent substitution of mailto and sms links with these native view controllers at the Cordova level.

**Closed by Kyle-Reis** 2021-04-05 22:11 UTC
