### ISSUE TITLE
registerAndEnrollAccount Timeout Followed by Success

### ISSUE THREAD

**Issue by LibertyDev18** [msintuneappsdk/ms-intune-app-sdk-ios#300] opened 2023-01-23 16:56 UTC
**Describe the bug:**
Making a call to registerAndEnrollAccount will result in a IntuneMAMEnrollmentStatusTimeout response (~30 seconds after making the call) followed by a IntuneMAMEnrollmentStatusNewPoliciesReceived response (~6-8 seconds after).

This happens consistently on devices that start to exhibit this behavior. Other devices will respond relatively quickly to the registerAndEnrollAccount call almost as if the impacted devices are being intentionally "throttled".

**To Reproduce**
1. Make call to registerAndEnrollAccount
2. In enrollmentRequestWithStatus just log the fact that IntuneMAMEnrollmentStatusTimeout is returned - this occurs ~30 seconds after the call to registerAndEnrollAccount
3. Wait 6-8 seconds and enrollmentRequestWithStatus will receive a IntuneMAMEnrollmentStatusNewPoliciesReceived response

**Expected behavior:**
Correctly configured app with good network connectivity would result in a IntuneMAMEnrollmentStatusNewPoliciesReceived and no timeout response.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro, iPhone 14 Pro Max, iPhone 7 Plus
 - OS: iOS 14 & iOS 16

**Intune App SDK for iOS (please complete the following information):**
- 17.2.1
- Native

- Who is the customer?
- We are seeing this on devices across multiple device types and versions of iOS

**Additional context:**
In some cases uninstalling the app and reinstalling the app on the same device will result in no IntuneMAMEnrollmentStatusTimeout the next time through. If we uninstall and reinstall 24 hours later though the IntuneMAMEnrollmentStatusTimeout almost always occurs followed by a IntuneMAMEnrollmentStatusNewPoliciesReceived.

**Comment by LibertyDev18** [comment] 2023-01-31 19:55
Hi @Kyle-Reis, what logs can I help provide here for this issue? I enabled verbose logging for the SDK but not seeing much that will be helpful. After successfully authenticating the user with MSAL we make the call to registerAndEnrollAccount which results in a 216 response followed by a 100. Let me know what I can grab for you.

Thank you sir!

**Comment by LibertyDev18** [comment] 2023-02-01 15:25
Hi @Kyle-Reis, I implemented the diagnostics console in the app and am now seeing logs. I'm not sure if these will be helpful being that the issue is occurring on the call to get the app under management as opposed to occurring once the app is actually under management.

Let me know if you want me to use the tool to upload directly or supply logs on the side.

**Comment by LibertyDev18** [comment] 2023-02-01 16:32
Hi @Kyle-Reis, uploaded logs from the diagnostics console. Reference ID: A28E3C

**Comment by Kyle-Reis** [comment] 2023-02-03 03:32
Thanks for sharing the logs, @LibertyDev18. I'm looking into this.

**Comment by LibertyDev18** [comment] 2023-02-09 19:49
Hi @Kyle-Reis, following up to see if you've had a chance to look at this yet and if anything jumped out in the logs?

**Comment by Kyle-Reis** [comment] 2023-02-10 22:09
Hey @LibertyDev18 - Yes, this looks like it could be a threading issue in the SDK. We're still investigating the exact root cause and potential fix. Thanks for the logs. They're really helpful!

**Comment by LibertyDev18** [comment] 2023-02-23 21:48
Hi @Kyle-Reis, just bumping to see if there has been any progress here. Thanks!

**Comment by Kyle-Reis** [comment] 2023-02-23 23:41
Hey @LibertyDev18 - We now have a fix for this issue in review. It should go out in our next release.

**Comment by Kyle-Reis** [comment] 2023-02-27 21:59
Hey @LibertyDev18 - Our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 17.3.1) should resolve this issue.

**Comment by LibertyDev18** [comment] 2023-02-28 15:12
Hi @Kyle-Reis, that's awesome, thank you for the update. We'll get the latest version setup and do some testing to confirm.

**Comment by LibertyDev18** [comment] 2023-03-01 17:40
Hi @Kyle-Reis, can you confirm what the expected behavior is with the change/fix in place?

**Comment by Kyle-Reis** [comment] 2023-03-01 19:17
Hey @LibertyDev18 - In general, you should no longer get the timeout response that was occurring prior to the fix.

**Comment by LibertyDev18** [comment] 2023-03-03 21:26
Hey @Kyle-Reis, it does appear that the changes have resulted in a significant reduction in the number of timeout responses. We have only seen 3 timeouts in our testing so far and that is a huge improvement. We'll keep an eye on it but from our perspective this issue can be closed. Thanks for you help with this.

**Closed** 2023-03-03 21:46 UTC

**Comment by LibertyDev18** [comment] 2023-09-12 14:05
Hey @Kyle-Reis, we are seeing a significant amount of these types of delays again and was curious if there might have been an accidental regression in the code that maybe removed the associated fix here? One thing to note, it does seem like the delays are a bit longer now. I can spin up a new ticket but wanted to comment here for inline reference.

**Comment by LibertyDev18** [comment] 2023-09-14 17:49
Hi @Kyle-Reis, should have included that we are seeing this a lot in 17.6.3
