### ISSUE TITLE
OneDrive app not showing Mail managed app on the list while using Send a Copy

### ISSUE THREAD

**Issue by mdurini-swisscom** [msintuneappsdk/ms-intune-app-sdk-ios#214] opened 2021-11-05 07:58 UTC
Hello, i've tried to follow the steps suggested by @Kyle-Reis in [this](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/16) issue but i can't see mail app as destination for a "send a copy" action from onedive / office application. I don't get what i'm doing wrong:

the ios device (ipad) was enrolled using company portal
all the configuration policies (device restrictions and email profile) were correctly pushed to the device
Best regards

**Comment by abasore** [comment] 2021-11-09 14:39
Hi @mdurini-swisscom, are [these](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/16#issuecomment-433508882) the steps you followed for updating sending app protection policy? Since that post is relatively old, here are the [update docs](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios). 

If the updated steps still give you the issue, could you fill out the bug details template (below). They will help us narrow down what the issue could be. 

Bug Details Template: 
**Describe the bug:**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior:**
A clear and concise description of what you expected to happen. 

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**
Add any other context about the problem here.

**Comment by mdurini-swisscom** [comment] 2021-11-09 14:50
Hello @abasore , I investigated a little bit and I found that the problem is related to the options "Send org data to other apps" and "Receive data from other apps". The application "Mail" is visible only if both options are configured as "All apps". Once I change "Send org data to other apps" to "Policy managed apps with OS sharing", the Mail app will disappear.

I'm still able to attach Onedrive files an email from the Mail app itself, but the attachment are encrypted.

**Comment by abasore** [comment] 2021-11-10 13:39
@mdurini-swisscom, that sounds like expected behavior for when the native Mail app is not considered an iOS Managed App as described in [this example](https://docs.microsoft.com/en-us/mem/intune/apps/data-transfer-between-apps-manage-ios#example-2-end-user-experience) scenario.

Just to verify the policy configuration you are using, have you configured the IntuneMAMUPN key as described [here](https://docs.microsoft.com/en-us/mem/intune/apps/data-transfer-between-apps-manage-ios#configure-user-upn-setting-for-microsoft-intune-or-third-party-emm)? 

If needed, here is a tutorial doc for creating the email profile: https://docs.microsoft.com/en-us/mem/intune/configuration/quickstart-email-profile

**Comment by mdurini-swisscom** [comment] 2021-11-10 13:54
Hello @abasore,thank you for your reply. Yes, I already have an App Configuration Policy assigned to the following applications 

- Adobe Acrobat Reader
- Microsoft Edge
- Microsoft Outlook
- Microsoft PowerPoint
- Microsoft Office
- Microsoft OneNote
- Microsoft SharePoint
- Microsoft OneDrive
- Microsoft Teams
- Microsoft To-Do

and the key IntuneMAMUPN with the value {{UserPrincipalName}}. is it a bad approach to have only config for all the apps? in the documentation that you linked it seems that it will allow me to transfer data to iOS managed apps.

As you said, Mail app is not considered an iOS Managed App: how can I set it as managed one?

**Comment by abasore** [comment] 2021-11-12 13:53
@mdurini-swisscom having the configs for all the apps should allow you to transfer data as expected. Just to verify, have you made and deployed the [iOS Managed email profile](https://docs.microsoft.com/en-us/mem/intune/configuration/email-settings-configure)?

**Comment by mdurini-swisscom** [comment] 2021-11-12 22:51
Hello @abasore , yes, i've followed the procedure but the Mail app is not working as expected. 
In the meanwhile, one guy from the Microsoft Support Team replied to my ticket with the following answer. 

> I have research and and queried our Senior Engineers and can was confirmed that App Protection Policies (cut/copy/paste, Save As, managed browser controls, etc.) can only be used with apps that have integrated the Intune SDK to further protect corporate data. This_ means that App Protection Policies does not work with built-in native apps like iOS mail app. Please see our Lead Engineer talk about this here - [iOS Native VS Outlook - Microsoft Tech Community](https://techcommunity.microsoft.com/t5/microsoft-intune/ios-native-vs-outlook/m-p/335270)
> Hence, I can confirm that the reason iOS native Mail App can't send OneDrive files as attachments, is because iOS mail app is not integrated with the Intune SDK. We therefore suggest that you encourage your clients to move over to outlook for enhanced security capabilities. See [Data protection framework using app protection policies - Microsoft Intune | Microsoft Docs](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-framework)

 I would like to understand if what I'm trying to do is still possible or not? You didn't reply to my question regarding the approach to have only one app protection policy for all the apps with the key IntuneMAMUPN

**Comment by abasore** [comment] 2021-11-29 16:22
@mdurini-swisscom Members of my team have been able to repo the issue and we are looking into if this specific scenario is still supported. In regards to your question, having a single app protection policy assigned to several apps is a supported approach.

**Comment by abasore** [comment] 2021-11-29 22:10
@mdurini-swisscom to add some clarification for your question. It is supported to have a single [app protection policy](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy) assigned to several apps.

For [app config policy](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-overview) however, there are two variations: Managed Devices (MDM) app config and Managed Apps (MAM) app config. 

For managed apps (MAM) app config, multiple apps included in a single app configuration is supported. For managed devices (MDM) app config, **only a single target app per MDM app config is supported**. 

In order to use the IntuneMAMUPN key, MDM application config is required. Can you confirm if you are still seeing this issue when setting the IntuneMAMUPN key via MDM app config (not MAM app config). You can set the managed devices app config by going to the Endpoint Manager -> Apps -> Application Configuration Policy -> Add + -> "Managed Devices" -> Add target app (Onedrive, Outlooke etc.)

**Comment by abasore** [comment] 2021-12-16 20:13
@mdurini-swisscom Have you been able to resolve the issue with the steps above? Feel free to ask more questions here, otherwise I will go ahead and close this issue.

**Comment by abasore** [comment] 2021-12-27 13:47
Closing this issue for now, feel free to re-open if issue persists.

**Closed by abasore** 2021-12-27 13:47 UTC
