### ISSUE TITLE
Intune SDK integrated in iOS app with MAM policy applied, but still url not opening on edge browser as well as copy, share functionality is not working as per intune polices.

### ISSUE THREAD

**Issue by VivekKPatil** [msintuneappsdk/ms-intune-app-sdk-ios#294] opened 2022-12-12 10:58 UTC
I have integrated microsoft intune SDK in iOS application with MAM policy involved for login functionality as per MSAL.
MAM policies are working up to the mark, but there are some polisies not working properly.

issues:-
1) Open url on browser should be opened on EDGE browser but still it is opening in SAFARI browser.
2) Copy any kind of data from policies applied app to non secured app like notes, text, etc. should not restricted even after policies are applied.
3) For sharing any kind of file, image, etc. all options are available for sharing instead of secured policies applied applications.

can any one help in this issues

**Comment by Kyle-Reis** [comment] 2022-12-12 19:23
Hi @VivekKPatil - Are the following data policy settings configured as follows, and targeted to both the application and the account you are using to test?

For issue 1:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/7443106/207135545-c4a4a6ae-11a1-4ff6-9d8e-87d78edad51e.png">

Foe issue 2:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/7443106/207135597-959877a5-6d02-4406-bb08-63618d180d35.png">

For issue 3:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/7443106/207135475-bf2ea0b6-4bc0-44c9-83d4-b9577aea834a.png">

**Comment by Kyle-Reis** [comment] 2023-01-04 01:09
Closing out this issue as we were able to determine that the root cause was an invalid MSAL redirect URI under IntuneMAMSettings which was leading to enrollment failures.

**Closed by Kyle-Reis** 2023-01-04 01:09 UTC
