### ISSUE TITLE
iOS Intune SDK Not Honoring Dark Mode

### ISSUE THREAD

**Issue by jstefanich** [msintuneappsdk/ms-intune-app-sdk-ios#108] opened 2020-09-10 17:31 UTC
**Describe the bug:**
In the Microsoft documentation for the [iOS Intune SDK](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios), it references a setting called 'SupportsDarkMode' which should default to yes.  However, we are seeing an issue where the screens created by the Intune SDK only partially support dark mode.  This appears to be the case whether we leave the 'SupportsDarkMode' flag out altogether or add it and set it to 'YES'. For example, the primary background view looks to be defaulted to white, regardless of dark mode setting.  I believe it should be set to the iOS 'System Background Color' which will honor the user's dark mode preference.  

**To Reproduce**
1. Integrate Intune SDK into an app.
2. Implement any functionality that will cause the Intune SDK to take over UI (ex. non-silent register/enroll or de-register/unenroll) 
3. Ensure device is running dark mode
4. See error when Intune SDK takes over UI

**Expected behavior:**
All portions of the UI should honor user's dark mode preference when 'SupportsDarkMode' flag is either set to YES or left out of Intune SDK settings.

**Screenshots and logs:**

_**Screenshot of Intune UI after Intune SDK 'deRegisterAndUnenrollAccount' with wipe:**_
![LogoutWipe](https://user-images.githubusercontent.com/4225229/92770996-23210d00-f360-11ea-9ad4-0920a661e78b.png)

**_Screenshot of Intune SDK 'Checking App Status' after enrollment restart.  (As you can see, some parts of screen, including progress text is honoring dark mode, while the primary background is not.):_**
![CheckingAppStatus](https://user-images.githubusercontent.com/4225229/92771473-8743d100-f360-11ea-957f-47b5c0050cea.png)

**_Screenshot of Intune SDK Unlock Screen after successfully enrolling/register.  (As you can see, this screen correctly honors dark mode.):_**
![UnlockScreen](https://user-images.githubusercontent.com/4225229/92771702-bb1ef680-f360-11ea-9324-bf0d8e636b68.png)

**Smartphone (please complete the following information):**
 - Device: Any iPhone supporting Dark Mode
 - OS: > iOS 13.0

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using?  **12.8.0** Are you using the latest version?  **Yes**
- What platform is your app based in (native, Xamarin based, Cordova, etc)?  **Native**
- For errors during build, does the app build without Intune SDK integration?  **N/A**
- For errors post build, does the app launch without being Intune SDK integrated?  **N/A**

- Who is the customer? **Any iOS user**
- Do you see a trend with it only being reproduced on a specific device?  **Only devices using dark mode**

**Comment by Kyle-Reis** [comment] 2020-09-10 20:17
Hey @jstefanich, thanks for reporting this issue. The root cause is understood and I'm currently working on a fix.

**Comment by Kyle-Reis** [comment] 2020-11-23 23:05
Hi @jstefanich, this issue should be addressed in our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (version 14.0.0).

**Closed** 2020-11-23 23:05 UTC
