### ISSUE TITLE
SecItemDelete crashes when using UTF-8 encoded string data with kSecAttrService

### ISSUE THREAD

**Issue by rperry2** [msintuneappsdk/ms-intune-app-sdk-ios#167] opened 2021-05-18 19:22 UTC
**Describe the bug:**
Intune_secItemDelete crashes with an unrecognized selector for caseInsensitiveCompare: if a NSData created from the string for the object of kSecAttrService. This works just fine when not using the Intune SDK and I am unable to change the behavior due to this occurring in an SDK.

**To Reproduce**
Go through the process of generating a keychain request using kSecClassGenericPassword
Using NSString's dataUsingEncoding: method convert the NSString into NSData
Pass the resulting dictionary to SecItemDelete

**Expected behavior:**
The data be converted into a string and progressing without crashing 

**Screenshots and logs:**
When it crashes the crash report is: -[NSConcreteMutableData caseInsensitiveCompare:]: unrecognized selector sent to instance 0x28e7b1dd0

**Smartphone (please complete the following information):**
 iPad Pro running iPadOS 14.4

**Intune App SDK for iOS (please complete the following information):**
Native iOS using SDK 14.1.3

**Additional context:**
Here is some sample code that can be used to show the issue once modified to use appropriate keychain

NSString *testKey = @"com.someone.crash";
NSMutableDictionary *keychainDict = [NSMutableDictionary dictionary];
[keychainDict setObject:(id)kSecClassGenericPassword forKey:(id)kSecClass];
NSData *keyData = [testKey dataUsingEncoding:NSUTF8StringEncoding];
[keychainDict setObject:keyData forKey:(id)kSecAttrAccount];
// Crash occurs du to this
NSString *serviceKey = [NSString stringWithFormat:@"%@_Service", testKey];
NSData *serviceData = [serviceKey dataUsingEncoding:NSUTF8StringEncoding];
[keychainDict setObject:serviceData forKey:(id) kSecAttrService];
[keychainDict setObject:(id)kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly forKey:(id) kSecAttrAccessible];
[keychainDict setObject:@(YES) forKey:(id)kSecReturnData];
SecItemDelete((__bridge CFDictionaryRef)keychainDict);

**Comment by Kyle-Reis** [comment] 2021-05-18 19:48
Hi @rperry2. According to [Apple's documentation](https://developer.apple.com/documentation/security/ksecattrservice?language=objc), the value associated with kSecAttrService should be a string. Have you tried reaching out to the developer of this framework to see if they can stop converting the string to an NSData object?

**Comment by rperry2** [comment] 2021-05-18 20:07
I may be able to, but the issue is since it works fine when using the built in keychain method it probably wouldn't change. I was thinking the Intune variant would work as the built in one it's replacing does

**Comment by Kyle-Reis** [comment] 2021-05-18 21:26
It doesn't crash, but I'm not sure if it actually works as intended? Is the framework storing and deleting data to/from the expected keychain group when they supply a NSData object?

**Comment by rperry2** [comment] 2021-05-19 13:51
It appears as though it does work correctly. I can add my test data to the keychain with secItemAdd and when I delete I get the success status response from the system's secIteDelete. Without adding it I get the expected not found value (-25300) when I try to delete it. I can't say for sure what they framework is doing with the key, but it does appear as though they're using it.

**Comment by rperry2** [comment] 2021-05-20 14:00
I'm really more concerned that the app crashes than whether or not the keychain actually used the data right now. Even if you just return an error if the invalid type is there would be preferable to just flat out crashing

**Comment by Kyle-Reis** [comment] 2021-06-02 21:54
Hey @rperry2, I now have a fix for this issue in review. Will let you know when I have any further updates.

**Comment by Kyle-Reis** [comment] 2021-06-30 14:13
Hi @rperry2 - this issue should be addressed in our [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (14.5.0). Please reach out again if you run into any more issues!

**Closed by Kyle-Reis** 2021-06-30 14:13 UTC

**Comment by gowthamrajc** [comment] 2023-09-01 13:34
@Kyle-Reis we getting the same crash in latest releases of Intune SDK. The crash is observed when our library(dynamic framework) tries to delete item from keychain. On a additional note our library is obfuscated using Guardsquare.
The same crash is not happening when we remove Intune SDK from our project.
