### ISSUE TITLE
Intunes with Xamairn forms + msal

### ISSUE THREAD

**Issue by viveknegi51288** [msintuneappsdk/ms-intune-app-sdk-ios#87] opened 2020-05-17 22:47 UTC
I have an application with msal configuration and now i need to add intune sdk, but after my splash screen its block , nothing happened , please provide some sample app with

Xamarin forms + msal + Intune SDK

**Comment by Kyle-Reis** [comment] 2020-05-20 17:52
Closing this issue out as it appears to be a duplicate of t[his one](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/41) in our Xamarin bindings repository.

**Closed by Kyle-Reis** 2020-05-20 17:52 UTC
