### ISSUE TITLE
Unable to export .ipa file from Archive (Xcode 11)

### ISSUE THREAD

**Issue by Nookaraju** [msintuneappsdk/ms-intune-app-sdk-ios#48] opened 2019-09-10 05:01 UTC
---
name: Bug report
about: Unable to prepare .ipa file from Archive (Xcode 11 GM)
title: ''
labels: ''Intune MAM lib
assignees: ''

**Describe the bug:**
We are using Xcode 11 beta (7) to build our app and its archiving but failing while exporting it as .IPA. When we checked the log files found below:

```
Scanning IPA...
2019-09-10 04:55:20 +0000  Assertion failed: Expected 4 archs in otool output:
/var/folders/79/_qq790xn31v4dbky4x329k74x5_ywx/T/IDEDistributionOptionThinning.~~~1oUepV/Payload/<app>.app/Frameworks/IntuneMAM.framework/IntuneMAM:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    39       5272   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK NO_REEXPORTED_DYLIBS 
```

**To Reproduce**
Build app including Intune MAM SDK and try to export from Xcode 11

**Expected behavior:**
There should be no export errors 

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? YES, Latest version 11.2.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
iOS native
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?

- Who is the customer? Infor
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Nookaraju** [comment] 2019-09-16 08:39
Still the same issue with Xcode 11 GM.

**Comment by Kyle-Reis** [comment] 2019-09-18 14:34
Hey @Nookaraju, have you followed [these instructions](https://docs.microsoft.com/intune/app-sdk-ios#submit-your-app-to-the-app-store) to strip out simulator symbols from the framework?

**Comment by Nookaraju** [comment] 2019-09-19 07:38
I do strip out the simulator archs while uploading to AppStore.

But I'm facing this while archiving for in-house distribution. I was able to do with Xcode 10.2.

But, on other note, Its better to publish intune lib through cocoa pods so that we don't need to worry about these simulator archs.

**Comment by Kyle-Reis** [comment] 2019-10-08 17:09
@Nookaraju, can you try with the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) (12.0.12)? Thanks!

**Comment by Tionit** [comment] 2019-10-09 04:37
The problem still exists with v12.0.12 (@Kyle-Reis ).

This is critical for us, because we have to release a new iOS 13 version of our app, but the signing for Enterprise Distribution only fails because of the Intune SDK with the following message: "_IPA processing failed_". We have already removed the simulator symbols as described. But it still doesn't work. We urgently need a solution!

This is the spot in the log file:
```
Assertion failed: Expected 4 archs in otool output:
/var/folders/pt/kfg7hrfn7vq7b0fzvv0dvsfm0000gn/T/IDEDistributionOptionThinning.~~~6Lpuqf/Payload/SCD.app/Frameworks/IntuneMAM.framework/IntuneMAM:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    39       5272   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK NO_REEXPORTED_DYLIBS
```

**Comment by Nookaraju** [comment] 2019-10-09 06:49
@Kyle-Reis  @Tionit 

The problem still exists with v12.0.12, but I'm able to archive and export if we remove the simulator symbols from lib.

**Comment by Kyle-Reis** [comment] 2019-10-09 20:07
@Nookaraju and @Tionit, the x86_64 CPU type in your previous comments suggests that the IntuneMAM binary still contains that simulator arch. Are you certain both i386 and x86_64 were removed from the binary and that you are linking against the binary that was output by the lipo command?

**Comment by Tionit** [comment] 2019-10-10 03:25
@Kyle-Reis Yes, I followed the instructions [here](https://docs.microsoft.com/intune/app-sdk-ios#submit-your-app-to-the-app-store) and removed i386 and x86_64 from the binary with this command:

`lipo ~/Desktop/IntuneMAM.framework/IntuneMAM -remove i386 -remove x86_64 -output ~/Desktop/IntuneMAM.device_only`

Is there anything else to consider?

**Comment by Kyle-Reis** [comment] 2019-10-18 19:46
@Tionit, did you try cleaning the build folder before rebuilding/archiving?

**Comment by Tionit** [comment] 2019-10-19 02:19
> @Tionit, did you try cleaning the build folder before rebuilding/archiving?

Yes, of course I did.

**Comment by hirenhcm** [comment] 2019-10-27 10:10
Had the same exact issue as mentioned in the first comment. 

Was able to make it work after removing i386 and x86_64 from `IntuneMAM.framework` .As mentioned [here](https://docs.microsoft.com/en-us/intune/developer/app-sdk-ios#submit-your-app-to-the-app-store)

After this i was able to archive my build for In-house Distribution.

I am using XCode 11.1.

**Comment by Nookaraju** [comment] 2019-11-01 05:18
If you added this Run Script in target's Build phases, then you don't need to worry about stripping simulator archs every time you build.



```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done

```

**Comment by adamledwards** [comment] 2019-11-05 10:06
I had the same issue too however I'm using swift so had strip the archs for IntuneMAMSwiftStub.framwork and IntuneMAM.famework.

**Comment by Kyle-Reis** [comment] 2019-11-06 15:56
Hey @adamledwards, just want to check and make sure you're using IntuneMAMSwift.framework + IntuneMAMSwiftStub.framework. IntuneMAM.framework is intended for all-Objective-C apps/extensions.

@Tionit are you still having issues?

**Comment by adamledwards** [comment] 2019-11-12 21:55
Hey @Kyle-Reis I can confirm that I'm using all 3 libraries in my project.

Thanks for reaching out.

**Comment by Kyle-Reis** [comment] 2019-11-14 23:31
@adamledwards 3 libraries? You should only need IntuneMAMSwift.framework and IntineMAMSwiftStub.framework.  If you have an app or extension that is entirely written in Objective-C, then you should use IntuneMAM.framework instead of those two.

**Comment by adamledwards** [comment] 2019-11-18 13:32
@Kyle-Reis Ohh I see, Thanks for the heads up. My app is a mixture of objective-c and swift. 
So I can remove IntuneMAM.framework and just keep IntuneMAMSwift.framework and IntineMAMSwiftStub.framework?

Sorry for the late reply GH is not sending out message alerts.

**Comment by Kyle-Reis** [comment] 2019-11-18 13:35
@adamledwards yep!

@Tionit - just checking in to see if you were aboe to get past this before closing out the issue.

**Closed** 2019-11-20 14:26 UTC
