### ISSUE TITLE
MSIntue SDK iOS app not redirecting after login and enrollment

### ISSUE THREAD

**Issue by MikeP0911** [msintuneappsdk/ms-intune-app-sdk-ios#297] opened 2022-12-23 00:47 UTC
After 14.3.5 Intune version,  IntuneMAMEnrollmentManager.Instance.LoginAndEnrollAccount(emailText); is not working.

1. LoginAndEnrollAccount should do authentication 

**Expected behavior:**
Authentication should be performed

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes 17.0.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? Xamarin based

The Intune Login is not happening and the screen is freezing.

**Comment by MikeP0911** [comment] 2022-12-23 02:44
Authentication is handled by Intune SDK and not by ADAL or MSAL.
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin
Developed with the help of the above link.

**Comment by MikeP0911** [comment] 2022-12-28 03:02
IntuneMAMEnrollmentManager.Instance.LoginAndEnrollAccount(emailText)

is not prompting the user for user name and password when Microsoft.Intune.MAM.Xamarin.iOS version is 17.1.1

it prompts for username and password when Microsoft.Intune.MAM.Xamarin.iOS version is 14.3.5

**Comment by Kyle-Reis** [comment] 2022-12-28 19:19
Closing out this issue as it appears to be a duplicate of this one:

https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/56#issuecomment-1366840498

We'll use the issue filed in the Xamarin repository to track it. Thanks!

**Closed by Kyle-Reis** 2022-12-28 19:19 UTC
