### ISSUE TITLE
UIDocumentInteractionController not displaying preview with "Send org data to other apps"  policy set

### ISSUE THREAD

**Issue by alexwalpole** [msintuneappsdk/ms-intune-app-sdk-ios#117] opened 2020-10-27 22:11 UTC
**Describe the bug:**

In our app the user can open PDFs that are downloaded then saved in `NSDocumentDirectory`. The document is then displayed to the user with `UIDocumentInteractionController`. When the app is managed and the "Send org data to other apps" policy is set to "All apps", this works fine. However, setting any other policy for "Send org data to other apps" causes the `UIDocumentInteractionController` to appear, but no document preview is displayed. 
 example: 

<img src="https://user-images.githubusercontent.com/30059432/97449238-d8575680-1907-11eb-8142-4fe3aa01939a.png" width=300><img src="https://user-images.githubusercontent.com/30059432/97449294-e5744580-1907-11eb-8cf2-3e583a6220f4.png" width=300>

note that in the second image that the share options are restricted and a thumbnail of the document is visible. 

Is there something else we need to implement to make this work as expected? 

Looking at the docs the sections [here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#share-data-via-uiactivityviewcontroller) under "Share Data via UIActivityViewController", the instructions did not seem relevant as our app does not expect to be "shared to" or "copied to" from other apps ( we don't have `CFBundleDocumentTypes` defined). Nor do we have any existing share or action extensions. 

**Expected behavior:**
I expect to still see the PDF in the `UIDocumentInteractionController`

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
13.0.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native

**Comment by alexwalpole** [comment] 2020-10-28 16:15
I noticed that the docs here: https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios?WT.mc_id=Portal-Microsoft_Intune#data-transfer mention that "If the user performs a managed open-in function and transfers a document, the data will be encrypted and unreadable." I suppose this is what's happening in our app, the data sent to the `UIDocumentInteractionController` is encrypted. Is there a suggested workaround for this?

**Comment by ShruthiAchutha** [comment] 2020-11-02 14:33
@alexwalpole can your provide a video or detailed repro steps? You should still be able to preview your document irrespective of outgoing policy if the document is saved within your app sandbox. Can you also share intune logs from your app by following the directions at https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#how-can-i-troubleshoot-my-app

**Comment by alexwalpole** [comment] 2020-11-04 15:22
[IntuneMAMDiagnosticFiles.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/5488621/IntuneMAMDiagnosticFiles.txt)

The steps in our app are to download the pdf and save it to `.documentDirectory` and then read the file from there to display in the `UIDocumentInteractionController`

**Comment by ShruthiAchutha** [comment] 2020-11-04 16:03
Thanks! Does this issue only happen on iOS14?

**Comment by alexwalpole** [comment] 2020-11-04 16:15
No, I am able to reproduce on iOS 13.4 simulator as well.

**Comment by abasore** [comment] 2020-11-06 14:52
@alexwalpole  Are you implementing the isExternalUrl delegate as described [here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#displaying-web-content-within-an-application)? Returning True to isExternalUrl triggers the Intune SDK to attempt to open the URL in Edge which would fail with this blank screen when any policy besides "All apps" is applied.

**Comment by alexwalpole** [comment] 2020-11-06 15:01
No we have not implemented that delegate.

**Comment by abasore** [comment] 2020-11-12 13:02
Thanks for reporting this @alexwalpole After some investigating we found that this is part of a known issue. A fix has been made and will be available in a future release which is expected to be out before the end of December.

**Comment by alexwalpole** [comment] 2020-11-12 14:22
Great, thanks for the update.

**Comment by abasore** [comment] 2021-01-13 14:43
Hello @alexwalpole. Can you confirm if using the newest release (14.0.0) resolves this issue for you?

**Comment by alexwalpole** [comment] 2021-01-13 17:23
14.0.0 does not resolve this issue.

**Comment by abasore** [comment] 2021-04-09 17:31
Hi @alexwalpole, could you confirm if the policy set to "None" still creates the issue for you in the latest version (14.3.5)? Also, does this issue only occur with "Send org data to other apps" policy set to "None"? Or does it also reproduce for policy set to "Policy Managed Apps"?

**Comment by alexwalpole** [comment] 2021-04-27 16:55
Hi @abasore. The issue occurs with "None" as well as "Policy managed apps". 

After upgrading to 14.3.5, I still am able to reproduce the issue. Interestingly, the issue does not occur on simulator but does when running on device. 

Also, are there any plans to make the sdk available through Carthage? Doing so would make the upgrade process less cumbersome

**Comment by abasore** [comment] 2021-11-02 11:44
Closing due to inactivity. Feel free to re-open as needed!

**Closed by abasore** 2021-11-02 11:44 UTC
